CHEMSLUDGE_COL = "Chemsludge_Key"
HEK_CELL_LINE = "HEKALOT9253"
HEPATOCYTE_CELL_LINE = "HEPATOCYTES_HUMAN_LOT_240604"
KPL4_ABCB1_OE = "KPL4_ABCB1_OE"
HT1376_ABCG2_KO = "HT1376_ABCG2_KO"
DEFAULT_EXCLUDED_FROM_GEOMEAN = frozenset({
    HEK_CELL_LINE,
    HEPATOCYTE_CELL_LINE,
    KPL4_ABCB1_OE,
    HT1376_ABCG2_KO,
})
